version: '3.8'
services:
  postgres-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devotel
    ports:
      - '5432:5432'
    volumes:
      - user-db-data:/var/lib/postgresql/data
volumes:
  user-db-data:
  profile-db-data:
