spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devotel
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      platform: postgres

  jackson:
    serialization:
      indent-output: true

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
